package org.cagrid.cql.cqlbuilder.gui;

import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import org.cagrid.cql.cqlbuilder.cqlquery.CQLQueryAssociation;
import org.cagrid.cql.cqlbuilder.cqlquery.CQLQueryCriterion;
import org.cagrid.cql.cqlbuilder.metadata.AssociationEdge;
import org.cagrid.cql.cqlbuilder.metadata.UMLClass;
import org.cagrid.cql.cqlbuilder.metadata.UMLClassAttribute;


public class CriterionAddEditWindow extends javax.swing.JDialog /*implements Runnable*/ {

    private UMLClass fUml;
    private boolean _okButtonClicked = false;
    private DefaultMutableTreeNode rootNode;
    private String title;

    /** Creates new form CriterionAddEdit */
    public CriterionAddEditWindow(UMLClass fUml, CQLQueryCriterion aCriterion, String title) {
        setModal(true);
        this.title=title;
        this.fUml = fUml;
        rootNode = new DefaultMutableTreeNode("<associated classes>");
        for (AssociationEdge umlAssociatedClass : fUml.getAssociations()) {
            DefaultMutableTreeNode associatedNode = new AssociationJTreeNode(umlAssociatedClass);
            rootNode.add(associatedNode);
        }
        
        
        boolean areThereAssociatedClasses = true;
        if (rootNode.getChildCount()<1){//no associated classes            
            rootNode = new DefaultMutableTreeNode("NO ASSOCIATED CLASSES");
            areThereAssociatedClasses=false;            
        }

        treeModel = new DefaultTreeModel(rootNode);

        initComponents();
        cAssociatedAttrs.setVisible(false);

        LinkedList<UMLClassAttribute> attrs = fUml.getAttributes();
        for (UMLClassAttribute attr : attrs) {
            cAttribute.addItem(attr);
        }

        rAssociatedClass.setSelected(false);
        rCurrClass.setSelected(true);
        cAssociatedAttrs.setEnabled(false);

        jTree1.setEnabled(false);
        
        if (aCriterion != null) {
            setCriterion(aCriterion);
        }

        labelUmlClass.setText("UML class name: "+this.fUml.getFullName());

        if (!areThereAssociatedClasses){//no associated classes
            rAssociatedClass.setEnabled(false);
        }
        
        setVisible(true);
    }

    public CQLQueryCriterion getCriterion() {
        if (_okButtonClicked) {
            CQLQueryCriterion cr = new CQLQueryCriterion();
            cr.set_predicate((String) cLogicRelation.getSelectedItem());
            cr.set_value(inputValue.getText());
            if (rCurrClass.isSelected()) {
                cr.set_attributeName(((UMLClassAttribute) cAttribute.getSelectedItem()).getName());                
            } else {
                Object[] tab = jTree1.getSelectionPath().getPath();
                LinkedList<CQLQueryAssociation> nestedAssocs = new LinkedList<CQLQueryAssociation>();
                for (int i = 1; i < tab.length - 1; i++) {
                    AssociationEdge assocEdge = (AssociationEdge) ((DefaultMutableTreeNode) tab[i]).getUserObject();
                    nestedAssocs.add(new CQLQueryAssociation(assocEdge.getUmlClass().getName(), assocEdge.getUmlClass().getPackageName(), assocEdge.getRoleName()));
                }
                cr.setAssociations(nestedAssocs, ((UMLClassAttribute) ((DefaultMutableTreeNode) tab[tab.length - 1]).getUserObject()).getName());
            }
            return cr;
        } else {
            return null;
        }
    }

    /**
     * Used while editing the criterion - this method the sets the old data
     * @param criterion
     */
    private void setCriterion(CQLQueryCriterion criterion) {
        if (!criterion.areAssociationsSet()) {
            String attrName = criterion.get_attributeName();
            for (int i = 0; i < cAttribute.getItemCount(); i++) {
                Object attr = cAttribute.getItemAt(i);
                if (attr instanceof UMLClassAttribute) {
                    if (attrName.equals(((UMLClassAttribute) attr).getName())) {
                        cAttribute.setSelectedIndex(i);
                        break;
                    }
                }
            }
            rCurrClass.setSelected(true);
            jTree1.setEnabled(false);            
            cAttribute.setEnabled(true);
        } else {
            
            rAssociatedClass.setSelected(true);
            //jTree1.setSelectionPath(criterion.get_selectionAssociationPath());
            jTree1.setEnabled(true);            
            cAttribute.setEnabled(false);
        }
        inputValue.setText(criterion.get_value());
        cLogicRelation.setSelectedItem(criterion.get_predicate());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panelAssociatedClass = new javax.swing.JPanel();
        cAssociatedAttrs = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        cAttribute = new javax.swing.JComboBox();
        rAssociatedClass = new javax.swing.JRadioButton();
        rCurrClass = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        DefaultComboBoxModel logicRelModel = new DefaultComboBoxModel(new String[]{"<select the logic relation>"});
        String[] tab = CQLQueryCriterion.getPredicates();
        for (String str:tab){
            logicRelModel.addElement(str);
        }
        cLogicRelation = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputValue = new javax.swing.JTextField();
        buttonSaveCriterion = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        labelUmlClass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(title);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Set the criterion"));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cAssociatedAttrs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<select the attribute>" }));

        jPanel2.setAutoscrolls(true);
        jPanel2.setPreferredSize(new java.awt.Dimension(562, 143));

        jTree1.setModel(treeModel);
        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelAssociatedClassLayout = new javax.swing.GroupLayout(panelAssociatedClass);
        panelAssociatedClass.setLayout(panelAssociatedClassLayout);
        panelAssociatedClassLayout.setHorizontalGroup(
            panelAssociatedClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAssociatedClassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cAssociatedAttrs, 0, 372, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );
        panelAssociatedClassLayout.setVerticalGroup(
            panelAssociatedClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAssociatedClassLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cAssociatedAttrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        /*javax.swing.GroupLayout myPanelLayout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(myPanelLayout);
        sg1 = myPanelLayout.createSequentialGroup();        
        myPanelLayout.setHorizontalGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(sg1));
        sg2 = myPanelLayout.createSequentialGroup();        
        myPanelLayout.setVerticalGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(sg2));*/

        /*myPanelLayout = new GridBagLayout();
        jPanel2.setLayout(myPanelLayout);
        myPanelLayoutConstraints = new GridBagConstraints();
        myPanelLayoutConstraints.gridx=0;
        myPanelLayoutConstraints.gridy=0;
        myPanelLayoutConstraints.fill = GridBagConstraints.HORIZONTAL;
        myPanelLayoutConstraints.anchor = GridBagConstraints.NORTH;
        myPanelLayoutConstraints.gridheight = GridBagConstraints.RELATIVE;
        myPanelLayoutConstraints.weightx=1;
        myPanelLayoutConstraints.weighty=1;
        myPanelLayoutConstraints.insets=new Insets(3, 10, 0, 10);*/

        cAttribute.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<select the attribute>" }));

        buttonGroup1.add(rAssociatedClass);
        rAssociatedClass.setText("query by associated class' attribute");
        rAssociatedClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAssociatedClassActionPerformed(evt);
            }
        });

        buttonGroup1.add(rCurrClass);
        rCurrClass.setSelected(true);
        rCurrClass.setText("query by current class' attribute");
        rCurrClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rCurrClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelAssociatedClass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cAttribute, javax.swing.GroupLayout.Alignment.LEADING, 0, 392, Short.MAX_VALUE)
                    .addComponent(rAssociatedClass, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                    .addComponent(rCurrClass, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rCurrClass, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cAttribute, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(rAssociatedClass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAssociatedClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText(" select logic relation predicate:");

        cLogicRelation.setModel(logicRelModel);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cLogicRelation, 0, 392, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cLogicRelation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText(" enter the value:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputValue, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        buttonSaveCriterion.setText("Save criterion");
        buttonSaveCriterion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveCriterionActionPerformed(evt);
            }
        });

        panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelUmlClass.setFont(new java.awt.Font("Tahoma", 1, 11));
        labelUmlClass.setText(" gov.cagrid.service.Experiment");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelUmlClass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelUmlClass, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(buttonSaveCriterion, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSaveCriterion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rCurrClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rCurrClassActionPerformed
        cAttribute.setEnabled(true);
        jTree1.setEnabled(false);        
}//GEN-LAST:event_rCurrClassActionPerformed

    private void buttonSaveCriterionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveCriterionActionPerformed
        boolean isPredicateNonValue = (CQLQueryCriterion.getNonValuePredicates().contains(cLogicRelation.getSelectedItem().toString()));
        if (rCurrClass.isSelected() && !(cAttribute.getSelectedIndex() > 0)) {
            JOptionPane.showMessageDialog(this.rootPane, "You must select an attribute", "", 0);
        } else if (rAssociatedClass.isSelected() && (jTree1.getSelectionPath() == null || (!(((DefaultMutableTreeNode) jTree1.getSelectionPath().getLastPathComponent()).getUserObject() instanceof UMLClassAttribute))) && !isPredicateNonValue) {
            JOptionPane.showMessageDialog(this.rootPane, "You must select an attribute of an assoicated classs", "", 0);
        } else if (!(cLogicRelation.getSelectedIndex() > 0)) {
            JOptionPane.showMessageDialog(this.rootPane, "You must select a logic relation", "", 0);
        } else if ("".equals(inputValue.getText()) && !isPredicateNonValue) {
            JOptionPane.showMessageDialog(this.rootPane, "You must enter a value", "", 0);
        } else {
            if (isPredicateNonValue) {
                inputValue.setText("");

            }
            _okButtonClicked = true;
            this.dispose();
        }
}//GEN-LAST:event_buttonSaveCriterionActionPerformed

    private void rAssociatedClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAssociatedClassActionPerformed
        cAttribute.setEnabled(false);
        jTree1.setEnabled(true);
        
    }//GEN-LAST:event_rAssociatedClassActionPerformed
    private DefaultTreeModel treeModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonSaveCriterion;
    private javax.swing.JComboBox cAssociatedAttrs;
    private javax.swing.JComboBox cAttribute;
    private javax.swing.JComboBox cLogicRelation;
    private javax.swing.JTextField inputValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel labelUmlClass;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelAssociatedClass;
    private javax.swing.JRadioButton rAssociatedClass;
    private javax.swing.JRadioButton rCurrClass;
    // End of variables declaration//GEN-END:variables
}

