package uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public interface NCBIBlastJobI {

  /**
   * Get the last error - if any
   *
   */
  public gov.nih.nci.cagrid.metadata.service.Fault getError() throws RemoteException ;

  /**
   * Get inputs used to submit this job
   *
   */
  public uk.org.mygrid.cagrid.domain.ncbiblast.NCBIBlastInput getInputs() throws RemoteException ;

  /**
   * Get outputs returned for this job, if any
   *
   */
  public uk.org.mygrid.cagrid.domain.ncbiblast.NCBIBlastOutput getOutputs() throws RemoteException ;

  /**
   * Get the current job status
   *
   */
  public uk.org.mygrid.cagrid.domain.common.Job getStatus() throws RemoteException ;

  public org.oasis.wsrf.lifetime.DestroyResponse destroy(org.oasis.wsrf.lifetime.Destroy params) throws RemoteException ;

  public org.oasis.wsrf.lifetime.SetTerminationTimeResponse setTerminationTime(org.oasis.wsrf.lifetime.SetTerminationTime params) throws RemoteException ;

  public org.oasis.wsn.SubscribeResponse subscribe(org.oasis.wsn.Subscribe params) throws RemoteException ;

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException ;

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException ;

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException ;

}

