package uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.client;

import java.rmi.RemoteException;

import org.apache.axis.client.Stub;
import org.apache.axis.message.addressing.EndpointReferenceType;
import org.apache.axis.types.URI.MalformedURIException;
import org.globus.gsi.GlobusCredential;

import uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.common.NCBIBlastI;

/**
 * This class is autogenerated, DO NOT EDIT GENERATED GRID SERVICE ACCESS METHODS.
 *
 * This client is generated automatically by Introduce to provide a clean unwrapped API to the
 * service.
 *
 * On construction the class instance will contact the remote service and retrieve it's security
 * metadata description which it will use to configure the Stub specifically for each method call.
 * 
 * @created by Introduce Toolkit version 1.3
 */
public class NCBIBlastClient extends NCBIBlastClientBase implements NCBIBlastI {	

	public NCBIBlastClient(String url) throws MalformedURIException, RemoteException {
		this(url,null);	
	}

	public NCBIBlastClient(String url, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(url,proxy);
	}
	
	public NCBIBlastClient(EndpointReferenceType epr) throws MalformedURIException, RemoteException {
	   	this(epr,null);
	}
	
	public NCBIBlastClient(EndpointReferenceType epr, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(epr,proxy);
	}

	public static void usage(){
		System.out.println(NCBIBlastClient.class.getName() + " -url <service url>");
	}
	
	public static void main(String [] args){
	    System.out.println("Running the Grid Service Client");
		try{
		if(!(args.length < 2)){
			if(args[0].equals("-url")){
			  NCBIBlastClient client = new NCBIBlastClient(args[1]);
			  // place client calls here if you want to use this main as a
			  // test....
			} else {
				usage();
				System.exit(1);
			}
		} else {
			usage();
			System.exit(1);
		}
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getMultipleResourceProperties");
    return portType.getMultipleResourceProperties(params);
    }
  }

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getResourceProperty");
    return portType.getResourceProperty(params);
    }
  }

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"queryResourceProperties");
    return portType.queryResourceProperties(params);
    }
  }

  public uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.types.NCBIBlastJobReference ncbiBlast(uk.org.mygrid.cagrid.domain.ncbiblast.NCBIBLASTInput nCBIBlastInput) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"ncbiBlast");
    uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.stubs.NcbiBlastRequest params = new uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.stubs.NcbiBlastRequest();
    uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.stubs.NcbiBlastRequestNCBIBlastInput nCBIBlastInputContainer = new uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.stubs.NcbiBlastRequestNCBIBlastInput();
    nCBIBlastInputContainer.setNCBIBlastInput(nCBIBlastInput);
    params.setNCBIBlastInput(nCBIBlastInputContainer);
    uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.stubs.NcbiBlastResponse boxedResult = portType.ncbiBlast(params);
    return boxedResult.getNCBIBlastJobReference();
    }
  }

  public uk.org.mygrid.cagrid.domain.common.SequenceDatabase[] getDatabases() throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getDatabases");
    uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.stubs.GetDatabasesRequest params = new uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.stubs.GetDatabasesRequest();
    uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.stubs.GetDatabasesResponse boxedResult = portType.getDatabases(params);
    return boxedResult.getSequenceDatabase();
    }
  }

}
