package uk.org.mygrid.cagrid.servicewrapper.service.interproscan.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class InterproScanWrappedImpl extends InterproScanWrappedImplBase {

	
	public InterproScanWrappedImpl() throws RemoteException {
		super();
	}
	

  public InterProScanOutput interProScan(InterProScanInput interProScanInput) throws RemoteException, null.Error {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

