package uk.org.mygrid.cagrid.servicewrapper.service.interproscan.job.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface InterproScanWrappedJobConstantsBase {
	public static final String SERVICE_NS = "gme://Taverna-caGrid.caBIG/1.0/uk.org.mygrid.cagrid.service.interproscan/Job";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "InterproScanWrappedJobKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "InterproScanWrappedJobResourceProperties");
	public static final QName INTERPROSCANOUTPUT = new QName("gme://Taverna-caGrid.caBIG/1.0/uk.org.mygrid.cagrid.domain.interproscan", "InterProScanOutput");
	public static final QName ERROR = new QName("gme://Taverna-caGrid.caBIG/1.0/uk.org.mygrid.cagrid.domain.common", "Error");
	public static final QName CURRENTTIME = new QName("http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd", "CurrentTime");
	public static final QName TERMINATIONTIME = new QName("http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd", "TerminationTime");
	
}
