/**
 * caGrid service wrapping of the public <a href=
 * "http://www.ebi.ac.uk/Tools/webservices/services/interproscan#runInterProScan"
 * >InterProScan service provided by EBI</a>
 * <p>
 * The public caGrid service is represented by
 * {@link net.sf.taverna.cagrid.servicewrapper.WrappedInterProScanService}.
 * <p>
 * The inputs and output of the caGrid service are to be defined by the UML
 * models to be provided separately as part of the caGrid-Taverna integration
 * project. The {@link net.sf.taverna.cagrid.servicewrapper.CaGridInterProScanInput} and
 * {@link net.sf.taverna.cagrid.servicewrapper.CaGridInterProScanOutput} beans are placeholders for the actual beans
 * to be autogenerated from the XMI files.
 * <p>
 * Internally the WrappedInterProScanService will use the
 * {@link net.sf.taverna.cagrid.servicewrapper.InterProScanDataConverter} to convert the input data to the format
 * expected by the actual WSDL service (placeholder {@link net.sf.taverna.cagrid.servicewrapper.InterProScanInput}),
 * use {@link net.sf.taverna.cagrid.servicewrapper.InterProScanServiceInvoker} to invoke the service, and convert the
 * output data (placeholder {@link net.sf.taverna.cagrid.servicewrapper.InterProScanOutput}) using the converter and
 * returning it to the caller of the caGrid service.
 */

package net.sf.taverna.cagrid.servicewrapper;