package uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class NCBIBlastImpl extends NCBIBlastImplBase {

	
	public NCBIBlastImpl() throws RemoteException {
		super();
	}
	
  public uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.stubs.types.NCBIBlastReference ncbiBlast(uk.org.mygrid.cagrid.domain.ncbiblast.NCBIBLASTInput nCBIBlastInput) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

