package uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class NCBIBlastJobImpl extends NCBIBlastJobImplBase {

	
	public NCBIBlastJobImpl() throws RemoteException {
		super();
	}
	
  public gov.nih.nci.cagrid.metadata.service.Fault getError() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public uk.org.mygrid.cagrid.domain.ncbiblast.NCBIBLASTInput getInputs() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public uk.org.mygrid.cagrid.domain.ncbiblast.NCBIBLASTOutput getOutputs() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public uk.org.mygrid.cagrid.domain.common.JobStatus getStatus() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

