package uk.org.mygrid.cagrid.servicewrapper.service.interproscan.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface InterproScanWrappedConstantsBase {
	public static final String SERVICE_NS = "gme://Taverna-caGrid.caBIG/1.0/uk.org.mygrid.cagrid.service.interproscan";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "InterproScanWrappedKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "InterproScanWrappedResourceProperties");
	public static final QName SERVICEMETADATA = new QName("gme://caGrid.caBIG/1.0/gov.nih.nci.cagrid.metadata", "ServiceMetadata");
	
}
