package uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.service.globus;

import uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.service.NCBIBlastJobImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the NCBIBlastImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class NCBIBlastJobProviderImpl{
	
	NCBIBlastJobImpl impl;
	
	public NCBIBlastJobProviderImpl() throws RemoteException {
		impl = new NCBIBlastJobImpl();
	}
	

    public uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetErrorResponse getError(uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetErrorRequest params) throws RemoteException {
    uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetErrorResponse boxedResult = new uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetErrorResponse();
    boxedResult.setFault(impl.getError());
    return boxedResult;
  }

    public uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetInputsResponse getInputs(uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetInputsRequest params) throws RemoteException {
    uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetInputsResponse boxedResult = new uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetInputsResponse();
    boxedResult.setNCBIBlastInput(impl.getInputs());
    return boxedResult;
  }

    public uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetOutputsResponse getOutputs(uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetOutputsRequest params) throws RemoteException {
    uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetOutputsResponse boxedResult = new uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetOutputsResponse();
    boxedResult.setNCBIBlastOutput(impl.getOutputs());
    return boxedResult;
  }

    public uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetStatusResponse getStatus(uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetStatusRequest params) throws RemoteException {
    uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetStatusResponse boxedResult = new uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetStatusResponse();
    boxedResult.setJob(impl.getStatus());
    return boxedResult;
  }

}
