package uk.org.mygrid.cagrid.servicewrapper.service.interproscan.job.service.globus;

import uk.org.mygrid.cagrid.servicewrapper.service.interproscan.job.service.InterproScanWrappedJobImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the InterproScanWrappedImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class InterproScanWrappedJobProviderImpl{
	
	InterproScanWrappedJobImpl impl;
	
	public InterproScanWrappedJobProviderImpl() throws RemoteException {
		impl = new InterproScanWrappedJobImpl();
	}
	

    public uk.org.mygrid.cagrid.servicewrapper.service.interproscan.job.stubs.GetStatusResponse getStatus(uk.org.mygrid.cagrid.servicewrapper.service.interproscan.job.stubs.GetStatusRequest params) throws RemoteException, null.Error {
    uk.org.mygrid.cagrid.servicewrapper.service.interproscan.job.stubs.GetStatusResponse boxedResult = new uk.org.mygrid.cagrid.servicewrapper.service.interproscan.job.stubs.GetStatusResponse();
    boxedResult.setResponse(impl.getStatus());
    return boxedResult;
  }

    public uk.org.mygrid.cagrid.servicewrapper.service.interproscan.job.stubs.GetOutputResponse getOutput(uk.org.mygrid.cagrid.servicewrapper.service.interproscan.job.stubs.GetOutputRequest params) throws RemoteException, null.Error {
    uk.org.mygrid.cagrid.servicewrapper.service.interproscan.job.stubs.GetOutputResponse boxedResult = new uk.org.mygrid.cagrid.servicewrapper.service.interproscan.job.stubs.GetOutputResponse();
    boxedResult.setInterProScanOutput(impl.getOutput());
    return boxedResult;
  }

    public uk.org.mygrid.cagrid.servicewrapper.service.interproscan.job.stubs.GetErrorResponse getError(uk.org.mygrid.cagrid.servicewrapper.service.interproscan.job.stubs.GetErrorRequest params) throws RemoteException, null.Error {
    uk.org.mygrid.cagrid.servicewrapper.service.interproscan.job.stubs.GetErrorResponse boxedResult = new uk.org.mygrid.cagrid.servicewrapper.service.interproscan.job.stubs.GetErrorResponse();
    boxedResult.setError(impl.getError());
    return boxedResult;
  }

}
