package uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.client;

import java.io.InputStream;
import java.rmi.RemoteException;

import javax.xml.namespace.QName;

import org.apache.axis.EngineConfiguration;
import org.apache.axis.client.AxisClient;
import org.apache.axis.client.Stub;
import org.apache.axis.configuration.FileProvider;
import org.apache.axis.message.addressing.EndpointReferenceType;
import org.apache.axis.types.URI.MalformedURIException;

import org.oasis.wsrf.properties.GetResourcePropertyResponse;

import org.globus.gsi.GlobusCredential;

import uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.NCBIBlastJobPortType;
import uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.service.NCBIBlastJobServiceAddressingLocator;
import uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.common.NCBIBlastJobI;
import gov.nih.nci.cagrid.introduce.security.client.ServiceSecurityClient;

/**
 * This class is autogenerated, DO NOT EDIT GENERATED GRID SERVICE ACCESS METHODS.
 *
 * This client is generated automatically by Introduce to provide a clean unwrapped API to the
 * service.
 *
 * On construction the class instance will contact the remote service and retrieve it's security
 * metadata description which it will use to configure the Stub specifically for each method call.
 * 
 * @created by Introduce Toolkit version 1.3
 */
public class NCBIBlastJobClient extends NCBIBlastJobClientBase implements NCBIBlastJobI {	

	public NCBIBlastJobClient(String url) throws MalformedURIException, RemoteException {
		this(url,null);	
	}

	public NCBIBlastJobClient(String url, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(url,proxy);
	}
	
	public NCBIBlastJobClient(EndpointReferenceType epr) throws MalformedURIException, RemoteException {
	   	this(epr,null);
	}
	
	public NCBIBlastJobClient(EndpointReferenceType epr, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(epr,proxy);
	}

	public static void usage(){
		System.out.println(NCBIBlastJobClient.class.getName() + " -url <service url>");
	}
	
	public static void main(String [] args){
	    System.out.println("Running the Grid Service Client");
		try{
		if(!(args.length < 2)){
			if(args[0].equals("-url")){
			  NCBIBlastJobClient client = new NCBIBlastJobClient(args[1]);
			  // place client calls here if you want to use this main as a
			  // test....
			} else {
				usage();
				System.exit(1);
			}
		} else {
			usage();
			System.exit(1);
		}
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}

  public gov.nih.nci.cagrid.metadata.service.Fault getError() throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getError");
    uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetErrorRequest params = new uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetErrorRequest();
    uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetErrorResponse boxedResult = portType.getError(params);
    return boxedResult.getFault();
    }
  }

  public uk.org.mygrid.cagrid.domain.ncbiblast.NCBIBLASTInput getInputs() throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getInputs");
    uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetInputsRequest params = new uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetInputsRequest();
    uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetInputsResponse boxedResult = portType.getInputs(params);
    return boxedResult.getNCBIBlastInput();
    }
  }

  public uk.org.mygrid.cagrid.domain.ncbiblast.NCBIBLASTOutput getOutputs() throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getOutputs");
    uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetOutputsRequest params = new uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetOutputsRequest();
    uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetOutputsResponse boxedResult = portType.getOutputs(params);
    return boxedResult.getNCBIBlastOutput();
    }
  }

  public uk.org.mygrid.cagrid.domain.common.JobStatus getStatus() throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getStatus");
    uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetStatusRequest params = new uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetStatusRequest();
    uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.job.stubs.GetStatusResponse boxedResult = portType.getStatus(params);
    return boxedResult.getJobStatus();
    }
  }

  public org.oasis.wsrf.lifetime.DestroyResponse destroy(org.oasis.wsrf.lifetime.Destroy params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"destroy");
    return portType.destroy(params);
    }
  }

  public org.oasis.wsrf.lifetime.SetTerminationTimeResponse setTerminationTime(org.oasis.wsrf.lifetime.SetTerminationTime params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"setTerminationTime");
    return portType.setTerminationTime(params);
    }
  }

  public org.oasis.wsn.SubscribeResponse subscribe(org.oasis.wsn.Subscribe params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"subscribe");
    return portType.subscribe(params);
    }
  }

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getMultipleResourceProperties");
    return portType.getMultipleResourceProperties(params);
    }
  }

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getResourceProperty");
    return portType.getResourceProperty(params);
    }
  }

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"queryResourceProperties");
    return portType.queryResourceProperties(params);
    }
  }

}
