package uk.org.mygrid.cagrid.servicewrapper.service.interproscan.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface InterProScanConstantsBase {
	public static final String SERVICE_NS = "http://www.mygrid.org.uk/2009/cagrid/servicewrapper/service/InterProScan";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "InterProScanKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "InterProScanResourceProperties");
	public static final QName SERVICEMETADATA = new QName("gme://caGrid.caBIG/1.0/gov.nih.nci.cagrid.metadata", "ServiceMetadata");
	
}
