package uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.service.globus;

import uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.service.NCBIBlastImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the NCBIBlastImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class NCBIBlastProviderImpl{
	
	NCBIBlastImpl impl;
	
	public NCBIBlastProviderImpl() throws RemoteException {
		impl = new NCBIBlastImpl();
	}
	

    public uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.stubs.NcbiBlastResponse ncbiBlast(uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.stubs.NcbiBlastRequest params) throws RemoteException {
    uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.stubs.NcbiBlastResponse boxedResult = new uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.stubs.NcbiBlastResponse();
    boxedResult.setNCBIBlastJobReference(impl.ncbiBlast(params.getNCBIBlastInput().getNCBIBlastInput()));
    return boxedResult;
  }

    public uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.stubs.GetDatabasesResponse getDatabases(uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.stubs.GetDatabasesRequest params) throws RemoteException {
    uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.stubs.GetDatabasesResponse boxedResult = new uk.org.mygrid.cagrid.servicewrapper.service.ncbiblast.stubs.GetDatabasesResponse();
    boxedResult.setDatabase(impl.getDatabases());
    return boxedResult;
  }

}
