package uk.org.mygrid.cagrid.servicewrapper.service.interproscan.job.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public interface InterproScanWrappedJobI {

  /**
   * Check status of job
   *
   * @throws Error
   *	
   */
  public java.lang.String getStatus() throws RemoteException, null.Error ;

  /**
   * getJobOutput
   *
   * @throws Error
   *	
   */
  public InterProScanOutput getOutput() throws RemoteException, null.Error ;

  /**
   * get error
   *
   * @throws Error
   *	
   */
  public Error getError() throws RemoteException, null.Error ;

  public org.oasis.wsrf.lifetime.DestroyResponse destroy(org.oasis.wsrf.lifetime.Destroy params) throws RemoteException ;

  public org.oasis.wsrf.lifetime.SetTerminationTimeResponse setTerminationTime(org.oasis.wsrf.lifetime.SetTerminationTime params) throws RemoteException ;

}

