package uk.org.mygrid.cagrid.servicewrapper.service.interproscan.job.service;

import java.rmi.RemoteException;

import uk.org.mygrid.cagrid.servicewrapper.serviceinvoker.InvokerException;
import uk.org.mygrid.cagrid.servicewrapper.serviceinvoker.interproscan.InterProScanInvoker;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class InterProScanJobImpl extends InterProScanJobImplBase {

	
	public InterProScanJobImpl() throws RemoteException {
		super();
	}
	
  public uk.org.mygrid.cagrid.domain.interproscan.InterProScanInput getInputs() throws RemoteException {
	 try {
		return getResourceHome().getAddressedResource().getInterProScanInput();
	} catch (Exception e) {
		e.printStackTrace();
		throw new RemoteException("Could not find input", e);
	}
  }

  public void getStatus(java.lang.String string) throws RemoteException {
	  String jobID;
	  try {
		jobID = getResourceHome().getAddressedResource().getJobID();
	} catch (Exception e) {
		throw new RemoteException("Unknown jobID", e);
	}
	InterProScanInvoker invoker;
	try {
		invoker = new InterProScanInvoker();
	} catch (InvokerException e1) {
		throw new RemoteException("Can't prepare InterProScan invocation", e1);
	}
	String status;
	try {
		status = invoker.checkStatus(jobID);
	} catch (InvokerException e) {
		throw new RemoteException("Could not check status for " + jobID, e);
	}
    System.out.println("Status is " + status);
  }

  public void getOutputs(uk.org.mygrid.cagrid.domain.interproscan.InterProScanOutput interProScanOutput) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public void getError(gov.nih.nci.cagrid.metadata.service.Fault fault) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

