package uk.org.mygrid.cagrid.servicewrapper.service.interproscan.job.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class InterproScanWrappedJobImpl extends InterproScanWrappedJobImplBase {

	
	public InterproScanWrappedJobImpl() throws RemoteException {
		super();
	}
	
  public java.lang.String getStatus() throws RemoteException, null.Error {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public InterProScanOutput getOutput() throws RemoteException, null.Error {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public Error getError() throws RemoteException, null.Error {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

